language: rust
dist: xenial
rust:
  - stable
  # - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - echo "$TRAVIS_RUST_VERSION" > rust-toolchain
  - rustup component add rustfmt
  - rustup show
script:
  - cargo fmt -- --check
  - cargo build -p testcrate
  - git submodule update --init --recursive
  - git clone https://github.com/onelson/jq-sys.git ../_jq-sys
  - mkdir ../.cargo
  - echo "paths = [\"$PWD\"]" > ../.cargo/config
  - cd ../_jq-sys
  - cargo test --features bundled

notifications:
  email: false
